### PR TITLE
XML documentation for NuGet package

### PR DESCRIPTION
**Pull request by gordey4doronin**
Hi,

It would be nice to have a documentation installed within the package from NuGet.
I've enabled XML documentation build option and added a reference in nuspec file.

_Of course it will need to rebuild, pack and publish a new NuGet package with bumped version._

**Before:**

zmq-without-documentation

**After:**

zmq-with-documentation

### CODE REVIEW

**Comment by metadings** [comment]
Yes, this is a good change! (You may just add more comments to the files.)

However, for rebuilding the NuGet package, I'd like to have a new version of `libzmq.dll` and `libzmq.so`. Because the Downloads section of zeromq.org is OUTDATED and I do just have a Linux computer, not a Windows computer, I am a bit of lost in this.

I consider to checkout the old version of libzmq v4.1.x, just because it has all the features I'd like to have (with curve and epgm). The version was made for MSVC2010 and GCC48.

**Comment by gordey4doronin** [comment]
> You may just add more comments to the files.

Did you mean to add more comments describing what my changes do?
I've just force pushed the branch with comments added.

What about `libzmq` version.
This project currently has `4.1.5` version.
While the latest version is `4.2.0`.
Is it critical?

By the way. There are 746 `CS1591 Missing XML comment for publicly visible type or member` warnings.

**Comment by metadings** [comment]
> Did you mean to add more comments describing what my changes do?

No...

> By the way. There are 746 CS1591 Missing XML comment for publicly visible type or member warnings.

This is what I mean, I don't have comments on each type or member. You may add more comments to the `.cs` files.

**Comment by gordey4doronin** [comment]
Hmm..

It's such a laborious task to add 700+ comments and not just auto-generated but comprehensible and clear enough.

I think better to create a new branch in the original repo (name it say `xml-doc`), and fill the comments bit by bit over time, forking and pull requesting to this very branch.

Also one should be familiar with what methods do to comment them properly.
While I am not familiar I could try help you anyway if I have time.

**Pull request merged**
