### PR TITLE
Changed ZFrame.ReadStringNative() to not mix character count and byte…

### PR DESCRIPTION
**Pull request by JochenLinnemann**
… count as MBCS like UTF-8 or -16 don't have a 1:1 relation between bytes and characters

### CODE REVIEW

**Comment by JochenLinnemann** [comment]
Works fine now...

**Comment by metadings** [comment]
You've changed and added a lot more, which I won't pull into the project...
Essentially, you changed

```
@@ -621,7 +621,9 @@ unsafe internal string ReadStringNative(int byteCount, Encoding encoding)
                return string.Empty;
            }

-           remaining = Math.Min(charCount, remaining);
+           // do not mix charCount and byteCount as multi-byte character sets
+           // like UTF-8 or UTF-16 do not have 1 byte per character (but more)!
+           //remaining = Math.Min(charCount, remaining);

            var resultChars = new char[charCount];
            fixed (char* chars = resultChars)
```

And yes, I've got a problem not with UTF-8, but with UTF-16 and UTF-32.... The main problem I'm facing is, that UTF-16 has a lot of NULs in there and in ReadString/ReadLine I'm cutting the string at the first NUL I'm seeing...

What ZeroMQ/clrzmq4 needs is to move ReadString/ReadLine into a ZFrameReader, which is initialized using the preferred Encoding. ZeroMQ/clrzmq4 also needs a ZFrameWriter, which writes on ZMessage/ZFrames.

**Comment by metadings** [comment]
Look, I'm leaving some time, because you could do a `git checkout ...` to the oldest commit I made, then do a `git pull origin master` and make your changes, `git add -A`, `git commit -m "Updating ZFrame.ReadStringNative"` and then you do a `git push origin master` - and create a new PR for this change.

I want you to be in the contributor's list; but if you don't mind, I'm going to make the (little) change...

**Comment by metadings** [comment]
OHA... It's awesome you branched this into "ZFrame-String-ReadWrite-EncodingDecoding"...

**Comment by metadings** [comment]
LOOK ! This again, is the moment I love GIT .... I was used to do

```
metadings@metadings-mint ~/ProjectZero/ZeroMQ $ git status
Auf Branch master
nichts zu committen, Arbeitsverzeichnis unverändert

metadings@metadings-mint ~/ProjectZero/ZeroMQ $ ls
amd64            RouterMandatory.cs        ZeroMQ.gif             ZError.cs            ZSocket.cs
AssemblyInfo.cs  TcpKeepaliveBehaviour.cs  ZeroMQ.ico             ZException.cs        ZSocketFlags.cs
bin              Z85.cs                    ZeroMQ.mono.csproj     ZFrame.cs            ZSocketOption.cs
Devices          ZActor.cs                 ZeroMQ.mono.userprefs  ZFrameOption.cs      ZSocketSetup.cs
i386             ZContext.cs               ZeroMQ.nuspec          ZMessage.cs          ZSocketType.cs
lib              ZContextOption.cs         ZeroMQ.Release.zip     ZPoll.cs             ZSymbol.cs
LICENSE.txt      ZDevice.cs                ZeroMQ.snk             ZPollItem.cs         ZThread.cs
Monitoring       ZeroMQ.4.1.0.19.nupkg     ZeroMQ.targets         ZPollItems.cs
obj              ZeroMQ.4.1.0.21.nupkg     ZeroMQ.VS.csproj       ZPollItems.Posix.cs
README.md        ZeroMQ.7z.Release.cmd     ZeroMQ.zip.Release.sh  ZPollItems.Win32.cs

metadings@metadings-mint ~/ProjectZero/ZeroMQ $ git checkout -b ZFrame-ReadStringNative
Zu neuem Branch 'ZFrame-ReadStringNative' gewechselt

metadings@metadings-mint ~/ProjectZero/ZeroMQ $ git remote -v
origin  ../.git/ZeroMQ.git/ (fetch)
origin  ../.git/ZeroMQ.git/ (push)
snapshot    git://192.168.123.10/ZeroMQ (fetch)
snapshot    git://192.168.123.10/ZeroMQ (push)
zeromq  git@github.com:zeromq/clrzmq4.git (fetch)
zeromq  git@github.com:zeromq/clrzmq4.git (push)

metadings@metadings-mint ~/ProjectZero/ZeroMQ $ git remote add JochenLinnemann https://github.com/JochenLinnemann/clrzmq4
```

Here I'm going to download your UPGRADE ...

```
metadings@metadings-mint ~/ProjectZero/ZeroMQ $ git pull JochenLinnemann ZFrame-String-ReadWrite-EncodingDecoding
remote: Counting objects: 12, done.
remote: Total 12 (delta 4), reused 4 (delta 4), pack-reused 8
Entpacke Objekte: 100% (12/12), Fertig.
Von https://github.com/JochenLinnemann/clrzmq4
 * branch            ZFrame-String-ReadWrite-EncodingDecoding -> FETCH_HEAD
 * [neuer Branch]    ZFrame-String-ReadWrite-EncodingDecoding -> JochenLinnemann/ZFrame-String-ReadWrite-EncodingDecoding
Aktualisiere 2e9fe08..e8ea80f
Fast-forward
 .gitignore                                     |  5 +++--
 ZFrame-EncodeDecode/App.config                 |  6 ++++++
 ZFrame-EncodeDecode/CodeMaid.config            | 31 +++++++++++++++++++++++++++++++
 ZFrame-EncodeDecode/Program.cs                 | 26 ++++++++++++++++++++++++++
 ZFrame-EncodeDecode/Properties/AssemblyInfo.cs | 36 ++++++++++++++++++++++++++++++++++++
 ZFrame-EncodeDecode/ZFrame-EncodeDecode.csproj | 66 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 ZFrame-EncodeDecode/ZeroMQ.VS.sln              | 28 ++++++++++++++++++++++++++++
 ZFrame.cs                                      |  4 +++-
 8 files changed, 199 insertions(+), 3 deletions(-)
 create mode 100644 ZFrame-EncodeDecode/App.config
 create mode 100644 ZFrame-EncodeDecode/CodeMaid.config
 create mode 100644 ZFrame-EncodeDecode/Program.cs
 create mode 100644 ZFrame-EncodeDecode/Properties/AssemblyInfo.cs
 create mode 100644 ZFrame-EncodeDecode/ZFrame-EncodeDecode.csproj
 create mode 100644 ZFrame-EncodeDecode/ZeroMQ.VS.sln

metadings@metadings-mint ~/ProjectZero/ZeroMQ $ git status
Auf Branch ZFrame-ReadStringNative
Änderungen, die nicht zum Commit vorgemerkt sind:
  (benutzen Sie "git add <Datei>...", um die Änderungen zum Commit vorzumerken)
  (benutzen Sie "git checkout -- <Datei>...", um die Änderungen im Arbeitsverzeichnis zu verwerfen)

    geändert:       ZFrame.cs

Unversionierte Dateien:
  (benutzen Sie "git add <Datei>...", um die Änderungen zum Commit vorzumerken)

    ZFrame-EncodeDecode/ZFrame-EncodeDecode.mono.csproj
    ZFrame-EncodeDecode/ZFrame-EncodeDecode.mono.sln

keine Änderungen zum Commit vorgemerkt (benutzen Sie "git add" und/oder "git commit -a")

metadings@metadings-mint ~/ProjectZero/ZeroMQ $ git status
Auf Branch ZFrame-ReadStringNative
Änderungen, die nicht zum Commit vorgemerkt sind:
  (benutzen Sie "git add/rm <Datei>...", um die Änderungen zum Commit vorzumerken)
  (benutzen Sie "git checkout -- <Datei>...", um die Änderungen im Arbeitsverzeichnis zu verwerfen)

    gelöscht:       ZFrame-EncodeDecode/App.config
    gelöscht:       ZFrame-EncodeDecode/CodeMaid.config
    gelöscht:       ZFrame-EncodeDecode/Program.cs
    gelöscht:       ZFrame-EncodeDecode/Properties/AssemblyInfo.cs
    gelöscht:       ZFrame-EncodeDecode/ZFrame-EncodeDecode.csproj
    gelöscht:       ZFrame-EncodeDecode/ZeroMQ.VS.sln
    geändert:       ZFrame.cs

keine Änderungen zum Commit vorgemerkt (benutzen Sie "git add" und/oder "git commit -a")
```

Now look: Here I've deleted the folder you've created, just changing the bits in `ZFrame.cs`:

```
@@ -621,7 +621,9 @@ unsafe internal string ReadStringNative(int byteCount, Encoding encoding)
                return string.Empty;
            }

-           remaining = Math.Min(charCount, remaining);
+           // do not mix charCount and byteCount as multi-byte character sets
+           // like UTF-8 or UTF-16 do not have 1 byte per character (but more)!
+           //remaining = Math.Min(charCount, remaining);

            var resultChars = new char[charCount];
            fixed (char* chars = resultChars)

metadings@metadings-mint ~/ProjectZero/ZeroMQ $ git add -A

metadings@metadings-mint ~/ProjectZero/ZeroMQ $ git commit -m "Updating ZFrame.ReadStringNative"
[ZFrame-ReadStringNative d60bde3] Updating ZFrame.ReadStringNative
 7 files changed, 197 deletions(-)
 delete mode 100644 ZFrame-EncodeDecode/App.config
 delete mode 100644 ZFrame-EncodeDecode/CodeMaid.config
 delete mode 100644 ZFrame-EncodeDecode/Program.cs
 delete mode 100644 ZFrame-EncodeDecode/Properties/AssemblyInfo.cs
 delete mode 100644 ZFrame-EncodeDecode/ZFrame-EncodeDecode.csproj
 delete mode 100644 ZFrame-EncodeDecode/ZeroMQ.VS.sln
```

Now the newly discovered CHECKOUT and MERGE ...

```
metadings@metadings-mint ~/ProjectZero/ZeroMQ $ git checkout master
Zu Branch 'master' gewechselt

metadings@metadings-mint ~/ProjectZero/ZeroMQ $ git merge ZFrame-ReadStringNative
Aktualisiere 2e9fe08..d60bde3
Fast-forward
 .gitignore | 5 +++--
 ZFrame.cs  | 2 --
 2 files changed, 3 insertions(+), 4 deletions(-)
metadings@metadings-mint ~/ProjectZero/ZeroMQ $ git status
Auf Branch master
nichts zu committen, Arbeitsverzeichnis unverändert
```

PUSH

```
metadings@metadings-mint ~/ProjectZero/ZeroMQ $ git push origin master & git push zeromq master
[1] 3148
Zähle Objekte: 15, Fertig.
Delta compression using up to 2 threads.
Komprimiere Objekte: 100% (14/14), Fertig.
Schreibe Objekte: 100% (15/15), 4.15 KiB | 0 bytes/s, Fertig.
Total 15 (delta 4), reused 0 (delta 0)
To ../.git/ZeroMQ.git/
   2e9fe08..d60bde3  master -> master
Zähle Objekte: 15, Fertig.
Delta compression using up to 2 threads.
Komprimiere Objekte: 100% (14/14), Fertig.
Schreibe Objekte: 100% (15/15), 4.15 KiB | 0 bytes/s, Fertig.
Total 15 (delta 4), reused 0 (delta 0)
To git@github.com:zeromq/clrzmq4.git
   2e9fe08..d60bde3  master -> master
[1]+  Done                    git push origin master
metadings@metadings-mint ~/ProjectZero/ZeroMQ $ 
```

**Comment by JochenLinnemann** [comment]
Thanks alot for your work!

**Comment by metadings** [comment]
Look, I have a bad internet connection (HSDPA) ... I need some time to re-build `ZeroMQ.mono.csproj` in `Release` mode, running `ZeroMQ.zip.Release.sh` and then uploading to GitHub.com/ZeroMQ/clrzmq4/releases and to nuget.org/packages/ZeroMQ !

**Comment by JochenLinnemann** [comment]
Let me know how (if) I can assist you. For my own immediate projects I currently use a custom-build version of ZeroMQ, so no need to hurry.

**Pull request merged**
