### PR TITLE
Include Mac OS X native binaries in repository and nuget packages

### PR DESCRIPTION
**Pull request by sigiesec**

### CODE REVIEW

**Comment by metadings** [comment]
TOP :smile:

**Comment by metadings** [comment]
Please look what about Linux `strip` - on MacOSX... Now the `dylib` is around 1 MB, on GNU/Linux the (stripped) `so` is 500 KB, on Windows the Release `dll` is also around 500 KB.

**Comment by metadings** [comment]
I'd also like that old binaries would really be *git* deleted... I do believe if you do `git clone` the project, all binaries, also the old ones are coming within *git*, gzipped...

**Comment by metadings** [comment]
Travis-CI says something like

	hh:mm:ss
	00:01:50	// GNU/Linux
	03:05:00	// Mac OS X

**Comment by metadings** [comment]
Do you also want to `git push` new Windows binaries (@sigiesec), or
should I directly start to make a new nuget package?

TOP :+1:

**Comment by sigiesec** [comment]
the windows binaries are up to date already

I can try to strip the MacOS binaries when I have access to a Mac again.

**Comment by sigiesec** [comment]
The Mac workers on Travis are very busy. also they need to install Mono etc. after they started which also takes quite some time

**Pull request merged**
