### PR TITLE
Support pyzmq under IronPython

### PR DESCRIPTION
**Pull request by swn1**
I am submitting this PR for discussion, the work is not 100% complete.  Also, the README and project file changes should probably not be included.

Together with some other repos (see https://github.com/IronLanguages/main/issues/1290#issuecomment-219049315), these changes enable importing and using the jupyter_client library in IronPython 2.7.5.

Discussion topic is, do the maintainers of clrzmq4 want to take this code on?

Counterpoint: I think I can probably go back and make it all work without introducing changes into clrzmq4.  It's cleaner this way (less replication of logic in the python glue layer) but avoiding pushing requirements into yet another repo is valuable too.

See https://github.com/IronLanguages/main/issues/1289 for difficulty of working around this injection.

Opinions?

### CODE REVIEW

**Comment by metadings** [comment]
I don't see any essential changes to ZeroMQ/clrzmq4 here... I see some backend classes, which are just wrapper classes... 

Did you do this because of using `IEnumerable<Byte>` instead of `byte[]`?

**Comment by swn1** [comment]
The problem I am struggling with is that the "bytes" type in IronPython is not compatible with the byte[] cts type.  So some kind of wrapper is needed on just about everything.

**Comment by metadings** [comment]
OHA... Well that's really BS for a language in .NET, not to support basic types...

However, I admit I like the use of `IEnumerable<Byte>` instead of `byte[]`...

But how would you use `ZFrame.Read(byte[] buffer, int offset, int count)` in IronPython? In C#

```
var buffer = new byte[5];
frame.Read(buffer, 0, 5);
```

**Comment by swn1** [comment]
It's supported, it's just not the type you get with the literal b"foo".  A lot of my pain has to do with the fact that it's Python 2.7 but str is unicode.  The other major source of pain is that it lacks a good way to bind to C libraries.  I picked clrzmq4 as a path to libxmq and ran headlong into this snarl.

I am far from expert in designing library interfaces in C#.  I am also pretty new to the whole zeromq code base.  My gut reaction is that talking about buffers at all is a sign of an unfortunate set of design choices but I don't have a good alternative in mind.

If I needed to call that method I'd allocate a mutable byte array http://www.ironpython.info/index.php?title=Typed_Arrays_in_IronPython . and then convert it either to str or bytes depending on what I was trying to do.  json_loads requires a str but most of the rest of jupyter_client operates in terms of the bytes type.

**Comment by swn1** [comment]
Looping back to your original comment, the pull request is all about re-wrapping the C# interface to be exactly what the pyzmq binding is looking for at the "backend" interface.  My other choices include
- using one of the other C#/clr binding packages
- binding to libzmq.dll directly from IronPython
- undertaking to make cffi work in IronPython
- tapping clrzmq4 at a lower level and implementing the pyzmq/backend interface in python

The 4th choice is where I was when I switched to the code you see in this PR.  The python code from the pyzmq/backend/cffi directory has the types needed, I just have to map what it needs onto the surface area of clrzmq4.  This is hard because of type mismatches and important intermediate facilities being marked "internal".

Release of the feature I was working on has been postponed so I'm going back to bullet 4 and see if I can make it work without modifying clrzmq4.  Unless you tell me that supporting the pyzmq/backend interface for IronPython is something you want to include here.

**Comment by metadings** [comment]
> tapping clrzmq4 at a lower level and implementing the pyzmq/backend interface in python

You should be going this way, using `ZeroMQ.lib.zmq` directly, because the changes will be really, really ugly.

**Pull request closed without merging**
