### PR TITLE
Updating ZeroMQ.lib.Platform

### PR DESCRIPTION
**Pull request by metadings**
Now defaulting to PlatformKind.NetCore.

### CODE REVIEW

**Comment by sigiesec** [comment]
The description is not quite clear to me. What does this PR try to achieve? Make support for .NET Core work?

Aren't you changing too much to achieve this? If I see this correctly, you are reverting the previous changes regarding the platform-specific library loading code. How is this related to making .NET Core work?

Note that the MacOS jobs on travis still do not work.

If we want to support .NET Core, it would be a good idea to also have CI for this. travis-ci supports that. See the documentation here: https://docs.travis-ci.com/user/languages/csharp/#Testing-Against-Mono-and-.NET-Core

**Comment by aerotog** [comment]
I've been watching this PR as it looks to be related to getting this running in Posix without Mono. @sigiesec, I think he is trying to do something similar to PR #138 (which was reverted) by replacing the Mono Internal calls with the more generic "libdl". The new platform is likely to make it optional so Mono can still be used.

I'm of the opinion that the project should be moved to .Net Standard first. By targeting Standard, we can have a single project that can be referenced by Framework, Mono and Core. Then we could make functional changes to make it work on Posix without Mono.

I have a fork compiling locally in .Net Standard. As of now it has no functional changes. The source files have been restructured due to how .Net Standard csproj work. I am in the process of testing it with our existing Framework projects. Once it's working, I was going to open a PR for review. I expect it to be rejected and/or fail CI tests as I don't have a way to test it against MacOS/Mono but would like to get feedback.

**Comment by aerotog** [comment]
@metadings, this brings back the various Platform classes that were removed in PR #142. Why?

**Comment by aerotog** [comment]
By the way, if you haven't seen it, PR #154 ports the project to .Net Standard which works with .Net Core, Framework and Mono.

**Pull request closed without merging**
