### PR TITLE
Xamarin iOS support

### PR DESCRIPTION
**Pull request by gillima**
# iPhone support

I implemented Platform.iOS and zmq.iOS to get clrzmq4 running on iPhones. `libzmq` and `libsodium` must be compiled as static libraries and added as native libraries to the Xamarin project.

### CODE REVIEW

**Comment by gillima** [comment]
As an idea the imports in class zmq could be generated by T4 at design time. This would reduce the effort to maintain separate platform imports.

**Comment by metadings** [comment]
Actually I don't like that you are copying the `class lib.zmq` around...

You did it because of `"__Internal"` instead of `"libzmq"`...

**Comment by gillima** [comment]
That's true and I fully agree. But I really didn't find any other way to achieve this. That's why I proposed the T4 thing. But this I didn't like because it's not working with MonoDevelop. Do you have any other idea how to do?

**Comment by metadings** [comment]
YEAH... I am going to change there some things... please wait :)

**Comment by gillima** [comment]
OK. I keep an eye on it. By the way, I had a code which was looking for the embedded libs in all loaded assemblies. What do you think about? It allows to embed without compiling zeromq. Shall I provide this as a separate pull request or do you don't like it at all?

**Comment by metadings** [comment]
> embedded libs in all loaded assemblies

Yes, well that is interesting... I could ask `HasLibraryInternal` in `Platform.SetupPlatformImplementation`...

I've now done some changes to CLRZMQ4, particularly in [`lib\Platform.cs`](https://github.com/zeromq/clrzmq4/blob/master/lib/Platform.cs), [`lib\Platform.__Internal.cs`](https://github.com/zeromq/clrzmq4/blob/master/lib/Platform.__Internal.cs) and also in [`lib\zmq.cs`](https://github.com/zeromq/clrzmq4/blob/master/lib/zmq.cs#L34), where I'm now doing

```
Platform.SetupPlatformImplementation(typeof(zmq));
```

to ensure the delegates are the `*__Internal` ones.

**Comment by metadings** [comment]
You are definitifly on the right track to CLRZMQ4... Please, just PR once

```
Platform.Win32.cs
22-             return Marshal.GetExceptionForHR(Marshal.GetHRForLastWin32Error());
22+             return new System.ComponentModel.Win32Exception();
```

**Comment by gillima** [comment]
Many thanks for the modifications. They are exactly what we need to support iPhones...
I found some small issues when testing on iOS and will create a PR.
- There is a problem with `SetupPlatformImplementation`. It overwrites the `__Internal` implementation of the `Platform` class with the `Posix` implementation (needed for `ZPollItem`). I had to change the priority of the implementation in case of `__Internal`.
- For some reason the check for `MonoTouch` using `GetType` isn't working anymore. I changed it to look for the `monotouch` or `Xamarin.iOS` assemblies (depending on MonoTouch version the assembly name has changed). I have tested it on IOS8 and IOS9, seems to work fine.
- The last change is (sorry, again) to replace `GetHRForLastWin32Error` with `Win32Exception`. This is for sure a Xamarin bug but replacing the method call with the exception should have exact the same result on Windows according to MSDN and will have no effect to the other platforms.

**Comment by metadings** [comment]
> GetHRForLastWin32Error with Win32Exception

Please make a PR with just this change.

**Comment by metadings** [comment]
> - There is a problem with SetupPlatformImplementation. It overwrites the __Internal implementation of the Platform class with the Posix implementation (needed for ZPollItem). I had to change the priority of the implementation in case of __Internal.

Yes, this problem remains... 
So what I need is to have `Kind = PlatformKind.Posix` and `Name = PlatformName.__Internal`...

**Comment by metadings** [comment]
Now I have `Kind = PlatformKind.Posix`, `Name = PlatformName.Posix` and also a `bool Is__Internal` which you can set to `true`... I'm preparing the platform, possibly overriding at least to __Internal...

Please try  `ZPollItems` again!

**Comment by gillima** [comment]
I added some logging as first line of `AssignImplementations`. Here you can see that the correct implementations are assigned to the classes. :thumbsup:

```
AssignImplementations(Type:Platform, ImplName:Posix)
AssignImplementations(Type:Platform, ImplName:__Internal)
AssignImplementations(Type:zmq, ImplName:Posix)
AssignImplementations(Type:zmq, ImplName:__Internal)
```

You have removed the check for `MonoTouch` which is a problem for us. We have old binding projects in our project and are actually not able to migrate from legacy API to the unified :weary: 
Would be very nice if the check for `MonoTouch` remains...

**Comment by metadings** [comment]
Okay, it's in ZeroMQ/clrzmq4 again.

**Pull request closed without merging**
