### PR TITLE
Updating libzmq.dll and lidsodium.dll

### PR DESCRIPTION
**Pull request by Chris-P-Bacon**
x64 & x86 build from HEAD revision of libzmq and libsodium.
The libzmq.dll is built without OpenPGM.

### CODE REVIEW

**Comment by metadings** [comment]
Well, it is fine you've compiled this project, but I don't want a quick-shot-build here.

I need them `VS2010` or `VS2012`, for `amd64` and `x86`, with `libsodium.dll` and `libpgm.lib`.

**Comment by metadings** [comment]
UPDATE: Now I see this is also compiled on `x86`.

My problem with this is: Why didn't you include `epgm`?

**Comment by metadings** [comment]
Also, You have registered for `github.com` a few days ago... I'm not going to `git pull` your compilation.

**Comment by Chris-P-Bacon** [comment]
I did not compile it with epgm, because I didn't know what it's used for (and didn't have the time to investigate). I can build it with epgm, if you want, but VS2010/2012 is not possible, since I only have VS2015. 
No offense, but isn't it a bit harsh to not accept contributions from me for the sole reason that I didn't bother contributing until now? Yes, it's binary stuff, but in what other form do want your dlls? ;-)

**Comment by metadings** [comment]
Yeah, you're right, actually I didn't worry about this...

However, I definitely need something older than VS2015... I also would like to have epgm, because there's no other way to multicast a ZFrame using ZeroMQ v4.1. In v4.2 will be UDP support (RADIO/DISH).

**Comment by Chris-P-Bacon** [comment]
Does the VS version really matter? It's a binary, after all.

**Comment by metadings** [comment]
It is a binary; depending on a VS version redistributable. VS2010 and VS2012 are more likely already installed, VS2015 not. Recently, Firefox switched from VS2010 to VS2012. And I don't need the latest shit, I need a program running everywhere. So yes, it does matter.

**Comment by Chris-P-Bacon** [comment]
Ah, ok. I wasn't aware that VC++ needs a runtime, too (We are using VC#). Thought we were talking about IDE versions. 
PS: Entschuldige bitte die Begriffsstutzigkeit. Wollte nur helfen ;-)

**Pull request closed without merging**
