### PR TITLE
Problems: failing Mono builds and  distracting message regarding sw_vers on Linux

### PR DESCRIPTION
**Pull request by sigiesec**
Solution: re-add ZeroMQTest.csproj to mono solution file, use uname instead of sw_vers

### CODE REVIEW

**Comment by metadings** [comment]
Please, not just your build.sh. I do NOT want to run `sh` and `sw_vars` in the source code, [lib/Platform.cs, Line 183](https://github.com/zeromq/clrzmq4/blob/bd441e7f52d571aaec9551d03a51c0ebbd81cbbf/lib/Platform.cs#L183), but instead just `uname`.

**Comment by metadings** [comment]
Also, the test on MacOSX is running ways too long. Is there no way to do these tests, without downloading a bunch of frameworks?

**Comment by metadings** [comment]
Your build is failing. Now what?

**Comment by metadings** [comment]
Your build is failing on Travis-CI.

**Comment by metadings** [comment]
Now Travis-CI is back again. I'm going to pull your request, so please do `git pull` and be fine.

Don't forget to fix the source in `lib/Platform.cs`, not just your `build.sh`.

**Comment by metadings** [comment]
Do you want to do this, or should I do change `lib/Platform.cs`?

I would check for a file `/System/Library/CoreServices/SystemVersion.plist`, if there is this file, this is MacOSX.

Or you do implement a P/Invoke to [`uname`](http://man7.org/linux/man-pages/man2/uname.2.html), with a try...catch if this method doesn't exist.
(Most likely you have to use `[DllImport("__Internal")]`, but I don't know if this method does exist on MacOSX.)

This would be much **much** better than creating a new process, each time you load the library.

**Comment by sigiesec** [comment]
I agree that creating an extra process to determine the OS is suboptimal.
Somehow calling uname via P/Invoke sounds better to me, since the check for the file somehow relies on kind of implementation details.

**Comment by metadings** [comment]
Well you're right with implementation details, however, this is just about MacOSX.
You would have to implement a lot more (fragil) code to use `uname`, just for "Darwin" MacOSX.

**Comment by sigiesec** [comment]
Sorry I just changed your comment, I wanted to change mine and did not see it popped up ;)

**Comment by sigiesec** [comment]
I found that it can be done in a simpler way. Mono provides System.Platform.IsMacOS (https://github.com/mono/mono/blob/47b285eac9b919cb1fc5eca4a162267f507c3890/mcs/class/System/System/Platform.cs#L78), which is implemented using uname. I will try to use that.

**Comment by metadings** [comment]
Well no, 1. the class `System.Platform` is internal, 2. this is just mono.

Please, do `if (Name == PlatformName.Posix && File.Exists(...` and good is.

**Comment by sigiesec** [comment]
That's right. Ok, I will check it via the file then.

**Pull request merged**
