### PR TITLE
Nuget Package uninstallable because nonclr assembly dependencies are poorly handled.

### PR DESCRIPTION
**Pull request by JamesTryand**
An existing issue with the way that nuget handles non clr dlls means that the nuget project doesn't load properly. 

Updating the project with respect to generating a nuget package, so that the non clr dependencies are handled correctly.  

For more details on the issue and its resolution see : http://stackoverflow.com/questions/19478775/add-native-files-from-nuget-package-to-project-output-directory

### CODE REVIEW

**Comment by metadings** [comment]
Hell is that ugly... For what is `RestoreNugetContent.ps1`?

**Comment by metadings** [comment]
I'm going to do a `nuget pack ZeroMQ.nuspec` and `nuget push ...`, or do I have to invoke something in PowerShell?

**Comment by metadings** [comment]
Okay, I've edited your PR by adding a version attribute:

	<dependency id="Baseclass.Contrib.Nuget.Output" version="0.0.2" />

**Comment by metadings** [comment]
I'm going to dislike your PR, the single "change" now left is `target="content\net40\"` to

``` xml
<file src="**" target="output\" exclude="bin\**\*.*;obj\**\*.*;amd64\v*\*.*;i386\v*\*.*;*.user;ZeroMQ.*.zip" />
```

**Comment by hintjens** [comment]
On Feb 20, 2015 12:56 AM, "Uli Riehm" notifications@github.com wrote:

> I'm going to dislike your PR...

:-) If you agree with the problem that the PR addresses, could you
propose a cleaner fix?

-Pieter

**Comment by metadings** [comment]
I've made the patch, it's the [change of the `target` attribute](https://github.com/zeromq/clrzmq4/blob/master/ZeroMQ.nuspec)...!

**Pull request merged**
