### PR TITLE
Updating lib.Platform: Name = PlatformName.MacOSX

### PR DESCRIPTION
**Pull request by metadings**
Enabling ZeroMQ/clrzmq4 to be used on MacOSX:

	static Platform()
	{	// ...

		if (Name == PlatformName.Posix && File.Exists("/System/Library/CoreServices/SystemVersion.plist")) 
		{
			Name = PlatformName.MacOSX;
		}

		// ...

### CODE REVIEW

**Comment by metadings** [comment]
Now look, I didn't know what C4 means.

I am NOT going to click on "merge pull request" (as I did in [ZeroMQ/clrzmq4/pull/129](https://github.com/zeromq/clrzmq4/pull/129#issuecomment-328471751)). 

Someone else is going to click on "merge pull request" @c-rack :smile:

**Comment by sigiesec** [comment]
@metadings Oh, I see now we both worked on this (my PR is #132). It took some time since the MacOS workers on travis-ci are very very busy.

The solution using the file did not work when I tried it unfortunately, probably because superuser permissions are required. Maybe I did something else wrong. Let's see if your build succeeds. If yes, I will take back my PR. Otherwise, I would suggest to use my PR #132.

**Comment by metadings** [comment]
Well, actually the method to detect MacOSX using File.Exists works! This is asking for .dylib files... (See the exception in Travis-CI's log!)

Could you make such .dylib files please? (Did this also run on .so files?)
Doesn't this copy the files into folder amd64?
Does MacOSX require dylib files somehow allowed to be run (chmod +x)?

**Comment by metadings** [comment]
Actually the method to detect MacOSX using `File.Exists` works!
This is asking for .dylib files... (See the exception in Travis-CI's log!)
(I took the file name from [stackoverflow.com: jariq's answer: Determine Operating System in .NET](https://stackoverflow.com/a/38795621/1352471).)
(This is managed C# AnyCPU and fully supported by all platforms, .NET Framework, .NET Core and mono framework.)

Could you make such .dylib files please? (Did this also run on .so files? :hushed:)

Does this also copy the file `libzmq.dylib` from folder `~/amd64` into `~/bin/Release/amd64`?

**Comment by sigiesec** [comment]
Yes, you are right. The reason the build failed is related to some problem before the build:
https://travis-ci.org/zeromq/clrzmq4/jobs/275772189#L920

libzmq.dylib is installed during the build. It is not copied into a subfolder at the moment. It would not really make sense to copy it into a folder named amd64, since .dylibs on MacOS are usually "universal binaries" that contain both 64bit and 32bit sub-libraries.

I will merge this, and see to fix the other problem.

**Comment by metadings** [comment]
Well, I made ZeroMQ/clrzmq4 to run either on folder i386, x86 OR on folder amd64, x64...

Please, could you copy the libzmq.dylib file into folder ~/amd64 (and do Copy if Newer)?
While it is not bad to have both binaries directly in one assembly, I'm doing so on Win32 and Posix.
Can you make this also happen on MacOSX?

If you push the dylib file to github, I'm going to make a new nuget package...!

(Could you also make a new Windows binary (preferably using MSVC2012 :smile:)?)

(I also do believe it would be better to have a fully working [zeromq4-1](https://github.com/zeromq/zeromq4-1),
instead of a cutting edge [libzmq](https://github.com/zeromq/libzmq)4-2.)

**Comment by metadings** [comment]
You also may hardcode `amd64` (or `MacOSX`) by replacing `{Arch}`, in `lib/Platform.MacOSX.cs`:

	namespace ZeroMQ.lib {
	public static partial class Platform {
		public static class MacOSX {
			// ...
			public static readonly string[] LibraryPaths = new string[] {
				"{AppBase}/amd64/{Compiler}/{LibraryName}.dylib",
				"{AppBase}/amd64/{Compiler}/{LibraryName}.dylib.*",
				"{AppBase}/amd64/{LibraryName}.dylib",
				"{AppBase}/amd64/{LibraryName}.dylib.*",
				"{DllPath}/{LibraryName}.dylib",
				"{DllPath}/{LibraryName}.dylib.*",
				"{Path}/{LibraryName}.dylib",
				"{Path}/{LibraryName}.dylib.*"
            		};
			// ...

**Pull request merged**
